kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: {{ .Values.s2i_runtime_image_namespace | quote }}
  annotations:
    description: Keeps track of changes in the application image
